### ISSUE TITLE
[BUG] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 15: invalid start byte

### ISSUE THREAD

**Issue by Canorus** [denBot/yasb#59]
## Expected Behavior
yasb should run when `python src/main.py` executed.

## Current Behavior
stops running with attached error meesage.

## Steps to Reproduce
1. git clone repository
2. run `python -m pip install -r requirements.txt --user`
3. run `python src/main.py`

## Context (Environment)

error message as below:

```
$ python src/main.py 
Yasb - Yet Another Status Bar
Starting KomorebiEventListener...
Starting SystemEventListener...
Created named pipe yasb-5f4d3e0a-59aa-11ed-818b-dcf505ca6af6
Created file watcher for path C:\Users\canor\.yasb
Waiting for Komorebi to subscribe to named pipe yasb-5f4d3e0a-59aa-11ed-818b-dcf505ca6af6
Traceback (most recent call last):
  File "C:\Users\canor\Downloads\yasb\src\core\utils\komorebi\event_listener.py", line 56, in run
    self._wait_until_komorebi_online()
  File "C:\Users\canor\Downloads\yasb\src\core\utils\komorebi\event_listener.py", line 100, in _wait_until_komorebi_online
    logging.warning(f"Komorebi failed to subscribe named pipe. Waiting for subscription: {stderr.decode('utf-8')}")
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 15: invalid start byte
```

- Windows10 20H2
- Python 3.11
- yasb version isn't unsure but just pulled from repository main branch so I assume it's the latest version as of 2022-11-01.

**Comment by Zoe-20** [comment]
may be you have not install komorebi
