### ISSUE TITLE
[BUG] Error Installing

### ISSUE THREAD

**Issue by liamtsang** [denBot/yasb#70]
When installing it gives this TypeError

λ python src/main.py

Traceback (most recent call last):
  File "src/main.py", line 3, in <module>
    from core.bar_manager import BarManager
  File "C:\Users\liamt\Documents\Python Scripts\yasb-main\src\core\bar_manager.py", line 7, in <module>
    from core.bar import Bar
  File "C:\Users\liamt\Documents\Python Scripts\yasb-main\src\core\bar.py", line 17, in <module>
    class Bar(QWidget):
  File "C:\Users\liamt\Documents\Python Scripts\yasb-main\src\core\bar.py", line 31, in Bar
    padding: dict = BAR_DEFAULTS['padding']
TypeError: 'type' object is not subscriptable

**Comment by liamtsang** [comment]
My ENV was still set to python 3.7 instead of 3.10 lol oops
